apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-agent
  labels:
    app: research-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: research-agent
  template:
    metadata:
      labels:
        app: research-agent
    spec:
      containers:
      - name: research-agent
        image: yourregistry.azurecr.io/research-agent:latest
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: research-agent-secrets
              key: openai-api-key
        - name: TAVILY_API_KEY
          valueFrom:
            secretKeyRef:
              name: research-agent-secrets
              key: tavily-api-key
        - name: USE_COSMOS_DB
          value: "true"
        - name: AZURE_COSMOS_ENDPOINT
          value: "https://your-cosmos.documents.azure.com:443/"
        - name: AZURE_COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: research-agent-secrets
              key: cosmos-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: research-agent-service
spec:
  selector:
    app: research-agent
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: research-agent-secrets
type: Opaque
stringData:
  openai-api-key: "your-openai-key-here"
  tavily-api-key: "your-tavily-key-here"
  cosmos-key: "your-cosmos-key-here"
